language: php

php:
- 5.4
- 5.5
- 5.6
- 7.0
- hhvm

env:
  global:
    secure: N6UFDGy6Rwm+l/zYtOvahgKRYx3QJyd4y6Iz9Q0D8bnthJIY1RkFRn3jiFrEZh+BcZNAQSf1uUnPHqN18hJ8Ay26Q7Lj6zWh5iNfKhpm6cY0tOOoECa1wOaJNc7YStq8/PupKTz0+vtPYsYXskyXsl4FyL9nUzoaVnYkCs2og2A=

before_script:
- composer require satooshi/php-coveralls:~0.6 --dev

script:
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
- php vendor/bin/coveralls -v
- if [ $TRAVIS_PHP_VERSION = '5.6' ]; then sh generate-api.sh; fi

notifications:
  email: false
